#生成的新镜像以centos镜像为基础
FROM centos:6.10
MAINTAINER by linguangde (lingd600@163.com)
RUN yum -y update
# 安装openssh-server
RUN yum -y install openssh-server
RUN mkdir /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
#指定root密码
RUN /bin/echo 'root:0406'|chpasswd
RUN /bin/sed -i 's/.*session.*required.*pam_loginuid.so.*/session optional pam_loginuid.so/g' /etc/pam.d/sshd
RUN /bin/echo -e "LANG=\"en_US.UTF-8\"" > /etc/default/local
RUN /bin/echo -n "PermitRootLogin yes" >> /etc/ssh/sshd_config
EXPOSE 22
CMD /usr/sbin/sshd -D